import { test } from "node:test";
import assert from "node:assert/strict";

import { isTspFrameText, isTspFrameBytes, TSP_MAGIC_BYTE, TSP_MAGIC_BYTE_LONG } from "../src/tsp-frame.js";
import * as base64url from "../src/base64url.js";

// ── Real frame heads ──
//
// Generated by `@openvtc/vti-tsp-js` 0.3.0 packing spec Rev 3 to
// did:web:alice.example -> did:web:bob.example, and pinned as bytes rather than
// imported: this library is a separate implementation of the same wire contract
// and must not take a dependency on the other one (that independence is the
// point — a shared helper would make both agree on a shared mistake).
//
// The two differ only in payload size, which is the whole story: 10 bytes gives
// an `-E` count under 4096 quadlets and a short header; 20 000 gives one over
// it and a long header. Every later byte is identical in structure —
// `YTSP-AAC`, then the sender VID.
const SHORT_HEAD = "f8403461348ff80002e010076469643a7765623a616c6963";
const LONG_HEAD = "fbe100001a3f61348ff80002e010076469643a7765623a61";

const bytes = (hex) => Uint8Array.from(Buffer.from(hex, "hex"));

test("a short-framed Rev 3 message is recognised in both domains", () => {
  const qb2 = bytes(SHORT_HEAD);
  assert.equal(qb2[0], TSP_MAGIC_BYTE);
  assert.equal(isTspFrameBytes(qb2), true);

  const text = base64url.encode(qb2);
  assert.ok(text.startsWith("-EA0"), `unexpected prefix ${text.slice(0, 6)}`);
  assert.equal(isTspFrameText(text), true);
});

test("a long-framed Rev 3 message is recognised in both domains", () => {
  // The regression this module exists for. Rev 3 widened the `-E` count to
  // cover the ciphertext, so a message past ~12 KB is long-framed — and the
  // check that used to live inline, `text.startsWith("-E")`, is false for it.
  const qb2 = bytes(LONG_HEAD);
  assert.equal(qb2[0], TSP_MAGIC_BYTE_LONG);
  assert.equal(isTspFrameBytes(qb2), true);

  const text = base64url.encode(qb2);
  assert.ok(text.startsWith("--EAAB"), `unexpected prefix ${text.slice(0, 6)}`);
  assert.equal(isTspFrameText(text), true);

  // Stated directly, because it is the bug: the old predicate rejected this.
  assert.equal(text.startsWith("-E"), false, "a long frame does not start -E");
});

test("both framings carry the same version marker, so neither is a different protocol", () => {
  // `YTSP-AAC` follows the count code in both. A reader that got the framing
  // right sees an identical message from there on; one that got it wrong never
  // reaches this far.
  for (const head of [SHORT_HEAD, LONG_HEAD]) {
    assert.ok(base64url.encode(bytes(head)).includes("YTSP-AAC"));
  }
});

test("DIDComm frames are not TSP", () => {
  for (const notTsp of [
    JSON.stringify({ protected: "x", ciphertext: "y" }), // JWE JSON
    "eyJhbGciOiJFZERTQSJ9.e30.sig", // compact JWS
    "",
    "-", // a lone dash is not a count code
    "-A", // a `-A` count code is a CESR group, not a TSP envelope
  ]) {
    assert.equal(isTspFrameText(notTsp), false, `classified as TSP: ${notTsp.slice(0, 12)}`);
  }
});

test("the classifier does not throw on junk input", () => {
  // It runs on every inbound frame before anything has validated the frame, so
  // a throw here would take out the receive loop rather than skip one message.
  for (const junk of [undefined, null, 42, {}, []]) {
    assert.equal(isTspFrameText(junk), false);
  }
  for (const junk of [undefined, null, new Uint8Array(0), []]) {
    assert.equal(isTspFrameBytes(junk), false);
  }
});

test("Rev 2's long form is deliberately not matched", () => {
  // `-0E…`: the second selector Rev 2 used, from a superseded draft of the CESR
  // v2 tables. Unreachable in practice — Rev 2's `-E` count covered only the
  // envelope header, so reaching a long count would take ~12 KB of VIDs — and
  // matching it would route to a TSP consumer a frame nothing can emit.
  const rev2Long = base64url.encode(bytes("fb4640001388"));
  assert.ok(rev2Long.startsWith("-0"), `unexpected prefix ${rev2Long.slice(0, 4)}`);
  assert.equal(isTspFrameText(rev2Long), false);
});

test("a Rev 2 short frame still routes — reading Rev 2 is not affected", () => {
  // The framing question is independent of the revision question. Rev 2 messages
  // are short-framed and start `-E`, exactly as they always did; what decodes
  // them is the consumer's problem, not this classifier's.
  const rev2 = bytes("f8401361348ff80001e010076469643a7765623a616c69");
  assert.equal(isTspFrameBytes(rev2), true);
  assert.equal(isTspFrameText(base64url.encode(rev2)), true);
});
